### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by alexklibisz** [samrose3/vue-portfolio#1]
Filer -> Filter

https://github.com/samrose3/vue-portfolio/blob/master/src/components/Projects/projects.js#L149

btw, very cool way to show your portfolio / history of work. I bet if you made it a stand-alone snippet / package people would use it!

**Comment by sam-b-rose** [comment]
@alexklibisz great catch! Thank you! And good idea... it wouldn't be hard to create a stand-alone template version as well.

**Comment by sam-b-rose** [comment]
closing with #2
